apiVersion: skaffold/v4beta2
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/client-depl.yaml
    - ./infra/k8s/ai-depl.yaml
    - ./infra/k8s/test-writer-depl.yaml
    - ./infra/k8s/rabbitmq-depl.yaml
    - ./infra/k8s/ingress-depl.yaml
build:
  local:
    push: false
  artifacts:
    - image: nericoder/autest/ai
      context: ai
      docker:
        dockerfile: Dockerfile
        noCache: true
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: nericoder/autest/test-writer
      context: test-writer
      docker:
        dockerfile: Dockerfile
        noCache: true
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: nericoder/autest/client
      context: client
      docker:
        dockerfile: Dockerfile
        noCache: true
      sync:
        manual:
          - src: "**/*.js"
            dest: .
#    - image: nericoder/autest/storify
#      context: storify
#      docker:
#        dockerfile: Dockerfile
#        noCache: true
#      sync:
#        manual:
#          - src: "src/**/*.ts"
#            dest: .
