apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-depl
spec:
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
        - name: ai
          image: nericoder/autest/ai
          env:
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: autest-exchanger-default-user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: autest-exchanger-default-user
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: autest-exchanger-default-user
---
apiVersion: v1
kind: Service
metadata:
  name: ai-srv
spec:
  selector:
    app: ai
  ports:
    - port: 3000
      targetPort: 3000
